# backend/Dockerfile
FROM python:3.11-slim

RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

# Entrypoint-Skript hinzufügen
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Port freigeben (optional)
EXPOSE 8000

# Entrypoint festlegen
ENTRYPOINT ["/entrypoint.sh"]

# Standardbefehl zum Starten des Servers
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
