# Generated by Django 5.1.1 on 2024-10-04 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='app.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='improvementsuggestion',
            name='analysis_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_suggestions', to='app.analysisresult'),
        ),
    ]
